Mark other VM imports as unsupported
dart-lang/dart-services pull request #642
Opened 2021-01-21 03:54 UTC by parlough

None of these have runtime support on web platforms, similar to `dart:io`.

2021-01-21 12:02 UTC, domesticmouse commented
@kevmoo does this look about right?

2021-01-21 17:39 UTC, kevmoo approved these changes

2021-01-21 17:39 UTC, kevmoo commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
although it might be better to do an allow list

2021-01-21 17:40 UTC, kevmoo commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
![image](https://user-images.githubusercontent.com/17034/105389412-ab47d680-5bcc-11eb-8b33-4119bf60e8bd.png)

2021-01-22 00:35 UTC, domesticmouse commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
@parlough I concur with @kevmoo's suggestion to use a whitelist.

@kevmoo is there a source for the list of supported libraries? It'd be useful to link to this location in the source code.

2021-01-22 01:00 UTC, kevmoo commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
dartdoc pulls it from somewhere - https://api.dart.dev/stable/2.10.5/index.html – @jcollins-g ?

2021-01-22 01:00 UTC, kevmoo commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
*cough* allowlist *cough* 😄

2021-01-22 02:06 UTC, parlough commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
If we're going with the `allowList` don't we need to include the web libraries as well here? For the HTML version of DartPad at least but even the flutter web version can use them, but a separate `info` is provided suggesting to only use them in packages.

I've gone ahead and included them, but let me know if you'd like to see any changes.

I didn't know how to programmatically retrieve the web-supported libraries, perhaps the analyzer can do so. As for the `dartdoc` functionality that seems to be due to Dartdoc categories, as can be seen here - https://github.com/dart-lang/sdk/blob/master/sdk/lib/mirrors/mirrors.dart#L56

2021-01-22 23:10 UTC, domesticmouse commented on lib/src/flutter_web.dart
> +      if (import.startsWith('dart:') && !_dartVmImports.contains(import)) {
Good point, we need to add `dart:html` and friends to the allow list, or a bunch of our samples will die an ignoble death. I believe we should add the following:

- `dart:html`
- `dart:indexed_db`
- `dart:js`
- `dart:js_util`
- `dart:svg`
- `dart:web_gl`
- `dart:web_sql`

Adding @johnpryan as sanity reviewer =)

2021-01-22 23:11 UTC, domesticmouse requested changes

2021-01-22 23:11 UTC, domesticmouse commented on lib/src/flutter_web.dart
> +    'dart:ui',
Add dart web imports plz

2021-01-22 23:12 UTC, parlough commented on lib/src/flutter_web.dart
> +    'dart:ui',
I believe they're in the list already, am I missing any?

2021-01-23 00:27 UTC, domesticmouse commented on lib/src/flutter_web.dart
> +    'dart:ui',
Whups, my bad. LGTM

2021-01-23 00:27 UTC, domesticmouse approved these changes

2021-01-23 00:28 UTC, domesticmouse commented
TBR @johnpryan

2021-01-23 00:29 UTC, merged